name: Build and test

on:
  push:
    branches: master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install
        run: npm cache clean --force && npm install --no-package-lock

      - name: Build
        run: npx spago build

      - name: Build and test project
        run: ./run_tests.sh

      - name: Build and test in headless browser
        run: ./run_headless_tests.sh
