name: Build and test

on:
  push:
    branches: master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install & build
        run: npm install && npx spago build

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
          path: |
            .spago
            output

      - name: Build and test project
        run: ./run_tests.sh

      - name: Build and test in headless browser
        run: ./run_headless_tests.sh
